### ISSUE TITLE
node app.js starter ikke

### ISSUE THREAD

**Issue by Centralize** [aroskanalen/middleware#1]
Når vi forsøger at køre node app.js, breaker den med følgende fejl:
os2display:/var/www/middleware# node app.js 

/var/www/middleware/app.js:71
    throw err;
          ^
TypeError: Cannot call method 'hasOwnProperty' of undefined
    at new Logger (/var/www/middleware/plugins/logger/logger.js:23:12)
    at Object.module.exports [as setup] (/var/www/middleware/plugins/logger/logger.js:171:16)
    at Architect.registerPlugin (/var/www/middleware/node_modules/architect/architect.js:491:16)
    at next (/var/www/middleware/node_modules/architect/architect.js:471:13)
    at Architect.loadPlugins (/var/www/middleware/node_modules/architect/architect.js:473:5)
    at /var/www/middleware/node_modules/architect/architect.js:421:13
    at process._tickCallback (node.js:458:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:945:3

os2display:/var/www/middleware# cat config.json 
{
    "port": 3020,
    "secret": "a9d93054d2e1f6992fe6174ae04011d0",
    "log": {
       "file": "messages.log",
       "debug": false
    },
    "admin": {
       "username": "admin",
       "password": "kodeord"
    },
    "cache": {
       "port": "6379",
       "host": "localhost",
       "auth": null,
       "db": 1
    },
    "apikeys": "apikeys.json"
}

os2display:/var/www/middleware# ls -la
total 76
drwxrwxr-x  8 www-data www-data 4096 Apr  7 12:35 .
drwxr-xr-x  8 root     root     4096 Apr  6 16:10 ..
-rw-rw-r--  1 www-data www-data  141 Apr  7 10:50 apikeys.json
-rw-rw-r--  1 www-data www-data 1405 Mar 30 14:02 app.js
-rw-rw-r--  1 www-data www-data  364 Apr  7 10:33 config.json
-rw-rw-r--  1 www-data www-data  140 Mar 30 14:06 example.apikeys.json
-rw-rw-r--  1 www-data www-data  472 Mar 30 14:02 example.config.json
drwxrwxr-x  8 www-data www-data 4096 Mar 30 14:06 .git
-rw-rw-r--  1 www-data www-data  110 Mar 30 14:02 .gitignore
drwxrwxr-x  2 www-data www-data 4096 Mar 30 14:02 gulp
-rwxrwxr-x  1 www-data www-data  183 Mar 30 14:02 install.sh
-rw-rw-r--  1 www-data www-data  450 Mar 30 14:02 .jshintrc
drwxrwxr-x  2 www-data www-data 4096 Apr  7 12:00 logs
-rwxrwxrwx  1 www-data www-data    0 Apr  6 17:13 messages.log
drwxrwxr-x  4 www-data www-data 4096 Apr  7 12:22 node_modules
-rw-rw-r--  1 www-data www-data  252 Apr  7 12:21 package.json
drwxrwxr-x 14 www-data www-data 4096 Mar 30 14:02 plugins
drwxrwxr-x  6 www-data www-data 4096 Mar 30 14:02 public
-rwxrwxr-x  1 www-data www-data  212 Mar 30 14:02 update.sh
-rwxrwxr-x  1 www-data www-data  237 Mar 30 14:02 upgrade.sh

**Comment by magnify** [comment]
Did you use the Installation Guide located here: https://github.com/os2display/docs/blob/development/Installation%20guide.md?

**Comment by magnify** [comment]
@nielsschmidt not sure who can answer this at the moment, the lead developers are afk.

Maybe we can get a comment from @cableman?

**Comment by Centralize** [comment]
@magnify Yep, absolutely.

**Comment by tuj** [comment]
It does not look as if your config.json matches the example.config.json.
https://github.com/os2display/middleware/blob/development/example.config.json

It is missing the 
"logs": {
    "info": "logs/info.log",
    "error": "logs/error.log",
    "debug": "logs/debug.log",
    "exception": "logs/exception.log",
    "socket": "logs/socket.log"
  },

**Comment by Centralize** [comment]
Efter ovenstående er rettet:
os2display:/var/www/middleware# node app.js

/var/www/middleware/app.js:71
    throw err;
          ^
TypeError: path must be a string
    at Object.fs.open (fs.js:430:11)
    at WriteStream.open (fs.js:1666:6)
    at new WriteStream (fs.js:1656:10)
    at Object.fs.createWriteStream (fs.js:1620:10)
    at new Logger (/var/www/middleware/plugins/logger/logger.js:25:29)
    at Object.module.exports [as setup] (/var/www/middleware/plugins/logger/logger.js:76:16)
    at Architect.registerPlugin (/var/www/middleware/node_modules/architect/architect.js:491:16)
    at next (/var/www/middleware/node_modules/architect/architect.js:471:13)
    at Architect.loadPlugins (/var/www/middleware/node_modules/architect/architect.js:473:5)
    at /var/www/middleware/node_modules/architect/architect.js:421:13

**Comment by tuj** [comment]
Har du oprettet mappen logs/ og har du skriveadgang?

**Comment by Centralize** [comment]
jeps mappen har været oprettet fra start af og permissions er 777 netop for at udelukke evtuelle skriverettighedsproblemer.

**Comment by tuj** [comment]
Hvordan ser din config ud nu her?

**Comment by Centralize** [comment]
{
    "port": 3020,
    "secret": "a9d92054d2f1f6992fe6174ae04011d0",
    "logs": {
      "info": "logs/info.log",
      "error": "logs/error.log",
      "debug": "logs/debug.log",
      "exception": "logs/exception.log",
      "socket": "logs/socket.log"
    },
    "admin": {
       "username": "admin",
       "password": "kodeord"
    },
    "cache": {
       "port": "6379",
       "host": "localhost",
       "auth": null,
       "db": 1
    },
    "apikeys": "apikeys.json"
}

**Comment by Centralize** [comment]
curl -XGET 'localhost:9200'
{
  "status" : 200,
  "name" : "Kiber the Cruel",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by tuj** [comment]
Middleware har ikke noget med elasticsearch at gøre.

**Comment by tuj** [comment]
Prøv at hacke: https://github.com/os2display/middleware/blob/development/plugins/logger/logger.js#L23

og se hvad logs variablen indeholder...

**Comment by Centralize** [comment]
Når jeg forsøger at køre app.js får jeg følgende:

os2display:/var/www/middleware# node app.js 

/var/www/middleware/app.js:71
    throw err;
          ^
TypeError: path must be a string
    at Object.fs.open (fs.js:430:11)
    at WriteStream.open (fs.js:1666:6)
    at new WriteStream (fs.js:1656:10)
    at Object.fs.createWriteStream (fs.js:1620:10)
    at new Logger (/var/www/middleware/plugins/logger/logger.js:25:29)
    at Object.module.exports [as setup] (/var/www/middleware/plugins/logger/logger.js:76:16)
    at Architect.registerPlugin (/var/www/middleware/node_modules/architect/architect.js:491:16)
    at next (/var/www/middleware/node_modules/architect/architect.js:471:13)
    at Architect.loadPlugins (/var/www/middleware/node_modules/architect/architect.js:473:5)
    at /var/www/middleware/node_modules/architect/architect.js:421:13

**Comment by tuj** [comment]
Kan du lave et 

console.log(logs);
console.log(path.join(__dirname, '../../' + logs.info));

før den her linje: https://github.com/os2display/middleware/blob/development/plugins/logger/logger.js#L23

og se hvad der kommer ud af det, når du kører app.js?

**Comment by Centralize** [comment]
Uden at vide præcis hvad jeg har gjort, kan jeg starte middleware app.js uden problemer.

**Comment by tuj** [comment]
Godt at det virker
