### ISSUE TITLE
search_node interface fejl

### ISSUE THREAD

**Issue by Centralize** [aroskanalen/middleware#2]
Jeg får en fejl i search_node interfacet, som måske hænger sammen med middleware fejlen, måske ikke.

![kazam_screenshot_00001](https://cloud.githubusercontent.com/assets/4147915/24797421/7f54a708-1b91-11e7-82ca-1d60f3edbb3d.png)

**Comment by Centralize** [comment]
Bump...

**Comment by tuj** [comment]
Hvilken version af search_node har du checket ud?
Vi kører v2.1.7 af search_node i produktion.

**Comment by tuj** [comment]
Elasticsearch should be version 1.7.1, not the newest version

**Comment by tuj** [comment]
Har du oprettet apikey og nogle søge indeks?

**Comment by Centralize** [comment]
curl -XGET 'localhost:9200'
{
"status" : 200,
"name" : "Kiber the Cruel",
"cluster_name" : "elasticsearch",
"version" : {
"number" : "1.5.2",
"build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
"build_timestamp" : "2015-04-27T09:21:06Z",
"build_snapshot" : false,
"lucene_version" : "4.10.4"
},
"tagline" : "You Know, for Search"
}

**Comment by Centralize** [comment]
Det har jeg forsøgt, men får ikke lov til at gemme api nøglen.

**Comment by tuj** [comment]
Har du lavet kopier af alle example filerne, i roden af projektet og udfyldt dem?

**Comment by Centralize** [comment]
jeps

**Comment by tuj** [comment]
Siger den det samme under ApiKeys siden?

**Comment by tuj** [comment]
Og har du nogle ikke aktiverede mappings i bunden af Indexes siden?
![screen shot 2017-04-24 at 10 11 29](https://cloud.githubusercontent.com/assets/6103205/25327984/7cf34dc8-28d6-11e7-91fb-aad2b09be68a.png)

**Comment by Centralize** [comment]
Jeg lukker denne, da lader til at fungere.

**Comment by tuj** [comment]
Ok
